# Generated by Django 4.1.5 on 2023-01-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('director', models.CharField(max_length=32)),
                ('mainActor', models.TextField()),
                ('genre', models.TextField()),
                ('starRating', models.FloatField()),
                ('runningTime', models.IntegerField()),
                ('reviewContent', models.TextField()),
                ('releaseYear', models.IntegerField()),
            ],
        ),
    ]
