# Generated by Django 4.1.5 on 2023-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.TextField(choices=[('action', '액션'), ('comedy', '코미디'), ('sf', 'SF'), ('drama', '드라마'), ('music', '음악'), ('romance', '로맨스'), ('history', '역사')], max_length=32),
        ),
    ]
